### ISSUE TITLE
Auto translation stops working after night service

### ISSUE THREAD

**Issue by AsteralD** [texel-sensei/CM3D2.AutoTranslate#6]
The translations work fine when starting the game but after each night service the translation stops working, no crashes just stops translating. I'm using your latest version and 1.52.2.134 game.

**Comment by texel-sensei** [comment]
Can you send me a logfile when the issue happens? It does really help to have one.
And sorry for not answering for so long, github somehow didn't send me an e-mail...

**Comment by AsteralD** [comment]
Where can I find the log you need? I'm not sure if the game creates a log when not crashing.

**Comment by texel-sensei** [comment]
You first need to enable logging in my plugin. Open the config file and change Debug/VerbosityLevel to 10 and Debug/LogToFile to True. This will create a logfile in UnityInjector/Config/Log/.

**Comment by AsteralD** [comment]
Here is the log you requested
[AutoTranslate.txt](https://github.com/texel-sensei/CM3D2.AutoTranslate/files/1241960/AutoTranslate.txt)

I'm not sure if this is the place to ask but would it be possible to extend the translation to the plugins aswell, as many of them are in japanese?

**Comment by texel-sensei** [comment]
Thanks. I don't know if I can fix that issue, because I don't have a setup with UnifiedTranslationLoader anymore to test things.

There is a new translation plugin, [YATranslator](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/custom-maid-3d-2-mods/5813782-plugin-yat-yet-another-translator-1-2-1-0-vpvr-subtitles-autotranslate), with that plugin it may be possible to also translate other plugins. But it doesn't work (yet) with AutoTranslate. But the author has released a patched version of my plugin that works, so it may be worth a try.

**Comment by AsteralD** [comment]
Thanks didn't know there were other ones out there, I managed to get YAT working, just as you said it works with a patched version of your plugin. Had to update cecil inject too, but got everything working flawlessy. Thanks for your effort into making this plugin, even if it has problems nobody can deny your effort and contribution to this small community!
